# The west manifest file for Harpoon Applications

manifest:
  defaults:
    remote: nxpmicro

  remotes:
    - name: nxpmicro
      url-base: https://github.com/NXPmicro
    - name: nxp
      url-base: https://github.com/NXP

  # Please add items below in reverse alphabetical order
  projects:
    - name: zephyr
      revision: aeb61cd2bd6d837d0161dc6174bde7279a9862f2
      import: true
    - name: mcux-sdk
      revision: 46d44c68e6cb7f97a68e6a1f75aaf4337dba90b5
    - name: GenAVB_TSN
      remote: nxp
      revision: 0fc0f1c854a1a7ad3199a053f607107f2b2a511f
      path: gen_avb_sdk
    - name: FreeRTOS-Kernel
      revision: 51e25b23a8738b8326cd751ef3063e7ec2544633
  self:
    path: harpoon-apps

