# The west manifest file for Harpoon Applications

manifest:
  defaults:
    remote: nxp

  remotes:
    - name: nxpzephyr
      url-base: https://github.com/nxp-zephyr
    - name: nxprealtimeedgesw
      url-base: https://github.com/nxp-real-time-edge-sw
    - name: nxpmcuxpresso
      url-base: https://github.com/nxp-mcuxpresso
    - name: nxp
      url-base: https://github.com/NXP

  projects:
    - name: zephyr
      remote: nxpzephyr
      revision: 3b58bc3af6bbfb27af49c3e8521ab7fb1415c271
    - name: mcux-sdk
      remote: nxpmcuxpresso
      revision: 463c99219dfd21d7c5e396657f1e92b91dd260c6
    - name: GenAVB_TSN
      revision: b0314e5da5fccc7b8b42411714adfdce9a8e2f5e
      path: gen_avb_sdk
    - name: hal_nxp
      remote: nxpzephyr
      revision: bee151b24100c3dd7b97ff29d2ecac23b9c52780
      path: modules/hal/nxp
      groups:
        - hal
    - name: FreeRTOS-Kernel
      remote: nxpmcuxpresso
      revision: 27bb9bb8ab283f2d802e28b485d4ca0531f66ba6
    - name: heterogeneous-multicore
      remote: nxprealtimeedgesw
      revision: fe7e5c1a932e38712ae5da167958aab8b43ae883
    - name: mcux-sdk-middleware-multicore
      remote: nxpmcuxpresso
      revision: e914909af2bf44fd651e3383ba0cd8cf5f0bda66
      path: middleware/multicore
    - name: rpmsg-lite
      remote: nxpmcuxpresso
      revision: 71bc60055fb02194b04ab4101795fa462444be87
      path: middleware/multicore/rpmsg_lite
  self:
    path: harpoon-apps

