# The west manifest file for Harpoon Applications

manifest:
  defaults:
    remote: nxp

  remotes:
    - name: nxpzephyr
      url-base: https://github.com/nxp-zephyr
    - name: nxprealtimeedgesw
      url-base: https://github.com/nxp-real-time-edge-sw
    - name: nxpmcuxpresso
      url-base: https://github.com/nxp-mcuxpresso
    - name: nxp
      url-base: https://github.com/NXP

  projects:
    - name: zephyr
      remote: nxpzephyr
      revision: d3644304707ef83fc34096454524fbda72f41ccb
    - name: mcux-sdk
      remote: nxpmcuxpresso
      revision: e44f3ae816e19743551ea6be28c1efba7d6f1905
    - name: GenAVB_TSN
      revision: 6aa2f518cd39425719c7374676e376d08c9d0358
      path: gen_avb_sdk
    - name: rtos-abstraction-layer
      revision: 10228a4b59d9811084dfc6eeec2ee162006a8338
      path: rtos-abstraction-layer
    - name: hal_nxp
      remote: nxpzephyr
      revision: 45ac8c57f22cd612a288a0416683efb251afad9e
      path: modules/hal/nxp
      groups:
        - hal
    - name: FreeRTOS-Kernel
      remote: nxpmcuxpresso
      revision: d2ca5ca56c79edac658773aa16cf0fd63e566a04
    - name: CMSIS_5
      remote: nxpmcuxpresso
      path: mcux-sdk/CMSIS
      revision: 66a180f8b67fb3fdd11271bb31f5abec42fa2f62
    - name: heterogeneous-multicore
      remote: nxprealtimeedgesw
      revision: d76985437c8324ed82845498847430e086253705
    - name: mcux-sdk-middleware-multicore
      remote: nxpmcuxpresso
      revision: 2d89233a3be1f9533bd948f33dd6d0275d72cedd
      path: middleware/multicore
    - name: rpmsg-lite
      remote: nxpmcuxpresso
      revision: b1e81b1aac8804119d552b6f4f813bea330f90cb
      path: middleware/multicore/rpmsg_lite
  self:
    path: harpoon-apps

