# The west manifest file for Harpoon Applications

manifest:
  defaults:
    remote: nxp

  remotes:
    - name: nxpzephyr
      url-base: https://github.com/nxp-zephyr
    - name: nxprealtimeedgesw
      url-base: https://github.com/nxp-real-time-edge-sw
    - name: nxpmcuxpresso
      url-base: https://github.com/nxp-mcuxpresso
    - name: nxp
      url-base: https://github.com/NXP

  projects:
    - name: zephyr
      remote: nxpzephyr
      revision: a050db46ae3d3322cb0cd61a8ca22cee3ef6d67a
    - name: mcux-sdk
      remote: nxpmcuxpresso
      revision: 0db10da15d9cc6222744d4854b2cb532b646dcd4
    - name: GenAVB_TSN
      revision: 609be86df6fd472c8b32e9eef201ffa2a0b46f78
      path: gen_avb_sdk
    - name: rtos-abstraction-layer
      revision: ccf7c68248b5ebef682eb4ef96434412087ccf5e
      path: rtos-abstraction-layer
    - name: hal_nxp
      remote: nxpzephyr
      revision: 4f076ac96a02a433265fbc1898a00f51449409a3
      path: modules/hal/nxp
      groups:
        - hal
    - name: FreeRTOS-Kernel
      remote: nxpmcuxpresso
      revision: c747fc1595cfc914021a6534adba86d6b152aac8
    - name: CMSIS_5
      remote: nxpmcuxpresso
      path: mcux-sdk/CMSIS
      revision: b5916939a8384aac3398e3f4ea97917fa9b030fd
    - name: heterogeneous-multicore
      remote: nxprealtimeedgesw
      revision: 8140eb0bb2f28219ed1c00cdcf5564abedf1f338
    - name: mcux-sdk-middleware-multicore
      remote: nxpmcuxpresso
      revision: 5b8772984399c3fa4c1bc3d530db09fef74349c7
      path: middleware/multicore
    - name: rpmsg-lite
      remote: nxpmcuxpresso
      revision: 436596cd4443d5cedd043291f45ac21504e70a4a
      path: middleware/multicore/rpmsg_lite
  self:
    path: harpoon-apps

