/*
 * FreeRTOS V202012.00
 * Copyright (C) 2020 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * http://www.FreeRTOS.org
 * http://aws.amazon.com/freertos
 *
 * 1 tab == 4 spaces!
 */

/* FreeRTOS includes. */
#include "FreeRTOS.h"
#include "task.h"

/* NXP includes. */
#include "fsl_device_registers.h"
#include "fsl_common.h"
#include "driver_arm_virtual_timer.h"

/*******************************************************************************
 * Global variables
 ******************************************************************************/

/*  computed once for all,  used to program the timer */
uint64_t FreeRTOS_tick_interval;

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*-----------------------------------------------------------*/

/*
 * Use the generic EL1 virtual timer for the tick interrupt.
 *
 * Note from ARM documentation[1]:
 *
 * When software writes TVAL, the processor reads the current system
 * count internally, adds the written value, and then populates CVAL:
 *
 *  CVAL = TVAL + System Counter
 *  Timer Condition Met: CVAL <= System Count
 *
 * [1] https://developer.arm.com/documentation/102379/0000/The-processor-timers
 */

void vConfigureTickInterrupt( void )
{
    uint64_t val;

    /* Initialize the device. */
    Timer_Init();

    /* Fetch timer frequency rate. */
    Timer_GetFreq(&val);

    /* Derive values from the tick rate. */
    FreeRTOS_tick_interval = val / configTICK_RATE_HZ;

    /* Set the timer tick interval. */
    Timer_SetInterval(FreeRTOS_tick_interval);

    /* Set the interrupt priority (must be the lowest possible). */
    /* FIXME: This function doesn't actually set the proper value when run from the inmate cell */
    GIC_SetPriority(ARM_GENERIC_TIMER_VIRTUAL_IRQn,
                portLOWEST_USABLE_INTERRUPT_PRIORITY << portPRIORITY_SHIFT);

    /* Enable the interrupt in the GIC. */
    GIC_EnableInterface();
    GIC_SetInterfacePriorityMask(portLOWEST_INTERRUPT_PRIORITY << portPRIORITY_SHIFT);
    GIC_EnableIRQ(ARM_GENERIC_TIMER_VIRTUAL_IRQn);

    /* Enable the interrupts in the timer. */
    Timer_EnableIRQ();

    /* Start the timer. */
    Timer_Start();
}
/*-----------------------------------------------------------*/

/*
 * The interrupts generated by the timer behave in a level-sensitive manner.
 * This means that, once the timer firing condition is reached, the timer
 * will continue to signal an interrupt until one of the following
 * situations occurs:
 *
 * o IMASK is set to one, which masks the interrupt.
 * o ENABLE is cleared to 0, which disables the timer.
 * o TVAL or CVAL is written, so that firing condition is no longer met.
 *
 * [Ref] https://developer.arm.com/documentation/102379/0000/The-processor-timers
 */
void vClearTickInterrupt( void )
{
    /* Set the timer tick interval. */
    Timer_SetInterval(FreeRTOS_tick_interval);
}
/*-----------------------------------------------------------*/

void vApplicationIRQHandler( uint32_t ulICCIAR )
{
    uint32_t ulInterruptID;

    /* In the 64-bit Cortex-A RTOS port it is necessary to clear the source
     * of the interrupt BEFORE interrupts are re-enabled. */
    // TODO: ClearInterruptSource();

    /* Re-enable interrupts. */
    __asm volatile( "MSR DAIFSET, #2" ); /* was "__asm volatile( "CPSIE I" );" */

    /* The ID of the interrupt is obtained by bitwise anding the ICCIAR value
    with 0x3FF. */
    ulInterruptID = ulICCIAR & 0x3FFUL;

    /* On the assumption that handlers for each interrupt are stored in an array
    called InterruptHandlerFunctionTable, use the interrupt ID to index to and
    call the relevant handler function. */

    switch (ulInterruptID) {

        case ARM_GENERIC_TIMER_VIRTUAL_IRQn:
             FreeRTOS_Tick_Handler();
             break;

        default: break;
    }
}
