/*
 * Copyright 2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_iomuxc.h"
#include "pin_mux.h"

#if (CONFIG_GENAVB_ENABLE == 1)
static void pin_mux_enet(void)
{
	IOMUXC_SetPinMux(IOMUXC_ENET_MDC_ENET1_MDC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_MDC_ENET1_MDC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U));
	IOMUXC_SetPinMux(IOMUXC_ENET_MDIO_ENET1_MDIO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_MDIO_ENET1_MDIO,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U));

	IOMUXC_SetPinMux(IOMUXC_ENET_RD0_ENET1_RGMII_RD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD0_ENET1_RGMII_RD0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));
	IOMUXC_SetPinMux(IOMUXC_ENET_RD1_ENET1_RGMII_RD1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD1_ENET1_RGMII_RD1,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));
	IOMUXC_SetPinMux(IOMUXC_ENET_RD2_ENET1_RGMII_RD2, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD2_ENET1_RGMII_RD2,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));
	IOMUXC_SetPinMux(IOMUXC_ENET_RD3_ENET1_RGMII_RD3, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD3_ENET1_RGMII_RD3,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_ENET_RX_CTL_ENET1_RGMII_RX_CTL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RX_CTL_ENET1_RGMII_RX_CTL,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_ENET_RXC_ENET1_RGMII_RXC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RXC_ENET1_RGMII_RXC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_ENET_TD0_ENET1_RGMII_TD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD0_ENET1_RGMII_TD0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(7U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(3U));
	IOMUXC_SetPinMux(IOMUXC_ENET_TD1_ENET1_RGMII_TD1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD1_ENET1_RGMII_TD1,
			IOMUXC_SW_PAD_CTL_PAD_DSE(7U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(3U));
	IOMUXC_SetPinMux(IOMUXC_ENET_TD2_ENET1_RGMII_TD2, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD2_ENET1_RGMII_TD2,
			IOMUXC_SW_PAD_CTL_PAD_DSE(7U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(3U));
	IOMUXC_SetPinMux(IOMUXC_ENET_TD3_ENET1_RGMII_TD3, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD3_ENET1_RGMII_TD3,
			IOMUXC_SW_PAD_CTL_PAD_DSE(7U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(3U));

	IOMUXC_SetPinMux(IOMUXC_ENET_TX_CTL_ENET1_RGMII_TX_CTL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TX_CTL_ENET1_RGMII_TX_CTL,
			IOMUXC_SW_PAD_CTL_PAD_DSE(7U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(3U));

	IOMUXC_SetPinMux(IOMUXC_ENET_TXC_ENET1_RGMII_TXC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TXC_ENET1_RGMII_TXC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(7U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(3U));
}
#endif /* #if (CONFIG_GENAVB_ENABLE == 1) */

void BOARD_InitPins(void)
{
	/* iomux for I2C3 */
	IOMUXC_SetPinMux(IOMUXC_I2C3_SCL_I2C3_SCL, 1U);
	IOMUXC_SetPinConfig(IOMUXC_I2C3_SCL_I2C3_SCL,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PE(1U));

	IOMUXC_SetPinMux(IOMUXC_I2C3_SDA_I2C3_SDA, 1U);
	IOMUXC_SetPinConfig(IOMUXC_I2C3_SDA_I2C3_SDA,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PE(1U));

	/* iomux for SAI3 */
	IOMUXC_SetPinMux(IOMUXC_SAI3_MCLK_SAI3_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_MCLK_SAI3_MCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_TXC_SAI3_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXC_SAI3_TX_BCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_TXD_SAI3_TX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXD_SAI3_TX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_TXFS_SAI3_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXFS_SAI3_TX_SYNC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	/* iomux for SAI5 */
	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD1_SAI5_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD1_SAI5_TX_SYNC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD2_SAI5_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD2_SAI5_TX_BCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD3_SAI5_TX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD3_SAI5_TX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD0_SAI5_RX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD0_SAI5_RX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(6U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(2U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

#if (CONFIG_GENAVB_ENABLE == 1)
	pin_mux_enet();
#endif
}
