/*
 * Copyright 2023 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_iomuxc.h"
#include "pin_mux.h"

void BOARD_InitPins(void)
{
	/*SAI3*/
	 IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO16__SAI3_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO16__SAI3_TX_BCLK, 
						IOMUXC_PAD_DSE(15U));
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO17__SAI3_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO17__SAI3_MCLK, 
						IOMUXC_PAD_DSE(15U));
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO19__SAI3_TX_DATA00, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO19__SAI3_TX_DATA00, 
						IOMUXC_PAD_DSE(15U));
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO20__SAI3_RX_DATA00, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO20__SAI3_RX_DATA00, 
						IOMUXC_PAD_DSE(15U));
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO26__SAI3_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO26__SAI3_TX_SYNC, 
						IOMUXC_PAD_DSE(15U));

	/*LPI2C1*/
	IOMUXC_SetPinMux(IOMUXC_PAD_I2C1_SCL__LPI2C1_SCL, 1U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_I2C1_SCL__LPI2C1_SCL, 
						IOMUXC_PAD_DSE(15U) |
						IOMUXC_PAD_FSEL1(2U) |
						IOMUXC_PAD_OD_MASK);
	IOMUXC_SetPinMux(IOMUXC_PAD_I2C1_SDA__LPI2C1_SDA, 1U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_I2C1_SDA__LPI2C1_SDA, 
						IOMUXC_PAD_DSE(15U) |
						IOMUXC_PAD_FSEL1(2U) |
						IOMUXC_PAD_OD_MASK);
}