/*
 * Copyright 2023-2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_iomuxc.h"
#include "pin_mux.h"

void BOARD_InitPins(void)
{
	/* Common SAI3 pins for the MX93AUD-HAT and the on-board codec */
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO16__SAI3_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO16__SAI3_TX_BCLK,
						IOMUXC_PAD_DSE(15U));

	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO17__SAI3_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO17__SAI3_MCLK,
						IOMUXC_PAD_DSE(15U));

	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO20__SAI3_RX_DATA00, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO20__SAI3_RX_DATA00,
						IOMUXC_PAD_DSE(15U));

	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO26__SAI3_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO26__SAI3_TX_SYNC,
						IOMUXC_PAD_DSE(15U));

	/* SAI3_RX_BCLK uses GPIO_IO18 for the MX93AUD-HAT */
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO18__SAI3_RX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO18__SAI3_RX_BCLK,
						IOMUXC_PAD_DSE(15U));

	/* SAI3_TX_DATA00 uses GPIO_IO21 for MX93AUD-HAT */
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO21__SAI3_TX_DATA00, 0U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO21__SAI3_TX_DATA00,
						IOMUXC_PAD_DSE(15U));

	/* LPI2C4 used for the MX93AUD-HAT */
	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO03__LPI2C4_SCL, 1U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO03__LPI2C4_SCL,
						IOMUXC_PAD_DSE(15U) |
						IOMUXC_PAD_FSEL1(2U) |
						IOMUXC_PAD_OD_MASK);

	IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO02__LPI2C4_SDA, 1U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO02__LPI2C4_SDA,
						IOMUXC_PAD_DSE(15U) |
						IOMUXC_PAD_FSEL1(2U) |
						IOMUXC_PAD_OD_MASK);

	/* LPI2C1 used for the on board-codec */
	IOMUXC_SetPinMux(IOMUXC_PAD_I2C1_SCL__LPI2C1_SCL, 1U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_I2C1_SCL__LPI2C1_SCL, 
						IOMUXC_PAD_DSE(15U) |
						IOMUXC_PAD_FSEL1(2U) |
						IOMUXC_PAD_OD_MASK);
	IOMUXC_SetPinMux(IOMUXC_PAD_I2C1_SDA__LPI2C1_SDA, 1U);
	IOMUXC_SetPinConfig(IOMUXC_PAD_I2C1_SDA__LPI2C1_SDA, 
						IOMUXC_PAD_DSE(15U) |
						IOMUXC_PAD_FSEL1(2U) |
						IOMUXC_PAD_OD_MASK);
}

void BOARD_pin_mux_dynamic_config(bool use_audio_hat)
{
	/* GPIO IO19 can only be used by the on-board codec or by the MX93AUD-HAT once */
	if (use_audio_hat) {
		IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO19__SAI3_RX_SYNC, 0U);
		IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO19__SAI3_RX_SYNC,
							IOMUXC_PAD_DSE(15U));
	} else {
		IOMUXC_SetPinMux(IOMUXC_PAD_GPIO_IO19__SAI3_TX_DATA00, 0U);
		IOMUXC_SetPinConfig(IOMUXC_PAD_GPIO_IO19__SAI3_TX_DATA00,
							IOMUXC_PAD_DSE(15U));
	}

}
