/*
 * Copyright 2022-2023, 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_iomuxc.h"
#include "pin_mux.h"
#include "rtos_apps/audio/audio_app.h"

void BOARD_InitPins(void)
{
	/* iomux for I2C3 */
	IOMUXC_SetPinMux(IOMUXC_I2C3_SCL_I2C3_SCL, 1U);
	IOMUXC_SetPinConfig(IOMUXC_I2C3_SCL_I2C3_SCL,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PE(1U));

	IOMUXC_SetPinMux(IOMUXC_I2C3_SDA_I2C3_SDA, 1U);
	IOMUXC_SetPinConfig(IOMUXC_I2C3_SDA_I2C3_SDA,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PE(1U));

	/* iomux for SAI3 */
	IOMUXC_SetPinMux(IOMUXC_SAI3_TXFS_AUDIOMIX_SAI3_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXFS_AUDIOMIX_SAI3_TX_SYNC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_TXC_AUDIOMIX_SAI3_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXC_AUDIOMIX_SAI3_TX_BCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_RXD_AUDIOMIX_SAI3_RX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_RXD_AUDIOMIX_SAI3_RX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_TXD_AUDIOMIX_SAI3_TX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXD_AUDIOMIX_SAI3_TX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_MCLK_AUDIOMIX_SAI3_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_MCLK_AUDIOMIX_SAI3_MCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_RXFS_GPIO4_IO28, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_RXFS_GPIO4_IO28,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_RXC_GPIO4_IO29, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_RXC_GPIO4_IO29,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	/* iomux for SAI5 */
	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD1_AUDIOMIX_SAI5_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD1_AUDIOMIX_SAI5_TX_SYNC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD2_AUDIOMIX_SAI5_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD2_AUDIOMIX_SAI5_TX_BCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD3_AUDIOMIX_SAI5_TX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD3_AUDIOMIX_SAI5_TX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD0_AUDIOMIX_SAI5_RX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD0_AUDIOMIX_SAI5_RX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));
}

void audio_app_pin_mux_dynamic_config(bool use_audio_hat) {
	return;
}
