/*
 * Copyright 2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "fsl_iomuxc.h"
#include "pin_mux.h"

#if (CONFIG_GENAVB_ENABLE == 1)
void pin_mux_enet_qos(void)
{
	/* ENET_QOS PHY RESET HPIO */
	IOMUXC_SetPinMux(IOMUXC_SAI2_RXC_GPIO4_IO22, 5U);
	IOMUXC_SetPinConfig(IOMUXC_SAI2_RXC_GPIO4_IO22,
	    IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
	    IOMUXC_SW_PAD_CTL_PAD_PE_MASK);

	/* MDC/MDIO */
	IOMUXC_SetPinMux(IOMUXC_ENET_MDC_ENET_QOS_MDC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_MDC_ENET_QOS_MDC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U));
	IOMUXC_SetPinMux(IOMUXC_ENET_MDIO_ENET_QOS_MDIO, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_MDIO_ENET_QOS_MDIO,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U));

	IOMUXC_SetPinMux(IOMUXC_ENET_RD0_ENET_QOS_RGMII_RD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD0_ENET_QOS_RGMII_RD0,
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
			IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_RD1_ENET_QOS_RGMII_RD1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD1_ENET_QOS_RGMII_RD1,
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
			IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_RD2_ENET_QOS_RGMII_RD2, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD2_ENET_QOS_RGMII_RD2,
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
			IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_RD3_ENET_QOS_RGMII_RD3, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RD3_ENET_QOS_RGMII_RD3,
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
			IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);

	IOMUXC_SetPinMux(IOMUXC_ENET_TD0_ENET_QOS_RGMII_TD0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD0_ENET_QOS_RGMII_TD0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_TD1_ENET_QOS_RGMII_TD1, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD1_ENET_QOS_RGMII_TD1,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_TD2_ENET_QOS_RGMII_TD2, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD2_ENET_QOS_RGMII_TD2,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_TD3_ENET_QOS_RGMII_TD3, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TD3_ENET_QOS_RGMII_TD3,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);

	IOMUXC_SetPinMux(IOMUXC_ENET_RXC_CCM_ENET_QOS_CLOCK_GENERATE_RX_CLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RXC_CCM_ENET_QOS_CLOCK_GENERATE_RX_CLK,
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
			IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_TXC_CCM_ENET_QOS_CLOCK_GENERATE_TX_CLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TXC_CCM_ENET_QOS_CLOCK_GENERATE_TX_CLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);

	IOMUXC_SetPinMux(IOMUXC_ENET_RX_CTL_ENET_QOS_RGMII_RX_CTL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_RX_CTL_ENET_QOS_RGMII_RX_CTL,
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
			IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
	IOMUXC_SetPinMux(IOMUXC_ENET_TX_CTL_ENET_QOS_RGMII_TX_CTL, 0U);
	IOMUXC_SetPinConfig(IOMUXC_ENET_TX_CTL_ENET_QOS_RGMII_TX_CTL,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
}
#endif /* #if (CONFIG_GENAVB_ENABLE == 1) */

void BOARD_InitPins(void)
{
	/* iomux for I2C3 */
	IOMUXC_SetPinMux(IOMUXC_I2C3_SCL_I2C3_SCL, 1U);
	IOMUXC_SetPinConfig(IOMUXC_I2C3_SCL_I2C3_SCL,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PE(1U));

	IOMUXC_SetPinMux(IOMUXC_I2C3_SDA_I2C3_SDA, 1U);
	IOMUXC_SetPinConfig(IOMUXC_I2C3_SDA_I2C3_SDA,
			IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PE(1U));

	/* iomux for SAI3 */
	IOMUXC_SetPinMux(IOMUXC_SAI3_TXFS_AUDIOMIX_SAI3_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXFS_AUDIOMIX_SAI3_TX_SYNC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_TXC_AUDIOMIX_SAI3_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXC_AUDIOMIX_SAI3_TX_BCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_RXD_AUDIOMIX_SAI3_RX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_RXD_AUDIOMIX_SAI3_RX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_TXD_AUDIOMIX_SAI3_TX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_TXD_AUDIOMIX_SAI3_TX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_MCLK_AUDIOMIX_SAI3_MCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_MCLK_AUDIOMIX_SAI3_MCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_RXFS_GPIO4_IO28, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_RXFS_GPIO4_IO28,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI3_RXC_GPIO4_IO29, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI3_RXC_GPIO4_IO29,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	/* iomux for SAI5 */
	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD1_AUDIOMIX_SAI5_TX_SYNC, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD1_AUDIOMIX_SAI5_TX_SYNC,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD2_AUDIOMIX_SAI5_TX_BCLK, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD2_AUDIOMIX_SAI5_TX_BCLK,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD3_AUDIOMIX_SAI5_TX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD3_AUDIOMIX_SAI5_TX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

	IOMUXC_SetPinMux(IOMUXC_SAI5_RXD0_AUDIOMIX_SAI5_RX_DATA0, 0U);
	IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD0_AUDIOMIX_SAI5_RX_DATA0,
			IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
			IOMUXC_SW_PAD_CTL_PAD_FSEL(1U) |
			IOMUXC_SW_PAD_CTL_PAD_PUE(1U) |
			IOMUXC_SW_PAD_CTL_PAD_HYS(1U));

#if (CONFIG_GENAVB_ENABLE == 1)
	pin_mux_enet_qos();
#endif
}
